### ISSUE TITLE
When device is put to sleep and memory card removed - device is soft-bricked

### ISSUE THREAD

**Issue by SilentSausage** [reswitched/fusee-launcher#18]
Found this out the hardway, if the device is put to sleep and the card is removed - device will not power back on until the battery is removed, to hard reset the device.

**Comment by DavidBuchanan314** [comment]
You can perform a hard reboot by holding the power button for ~12 seconds, did you try this first? (Standard hardlock recovery procecure)

I find it hard to imagine a scenario where a battery removal would work, but a hard reset would not.

**Comment by SilentSausage** [comment]
No I did not, I Held the power button for some time but I don't think it was for that long! If I have this issue again, I Will give this a go.

**Comment by jjbredesen** [comment]
Holding power for 12 seconds should always to recover from a freeze, it discharges the capacitors.

**Comment by Qyriad** [comment]
No response, and this would not be a problem of Fusée Launcher.
