### ISSUE TITLE
Typo in the fusee-launcher.py script ?!

### ISSUE THREAD

**Issue by falquinho** [reswitched/fusee-launcher#20]
https://github.com/reswitched/fusee-launcher/blob/433077ab727e41052bdd17693648a71087d8ac29/fusee-launcher.py#L546

Shouldn't  
`switch.get_current_buffer_address()`
be 
`self.get_current_buffer_address()`
?

**Comment by soramente** [comment]
It gets called later in line 674 as switch.switch_to_highbuf()

Before this, switch is set in line 592, here
`try:
    switch = RCMHax(wait_for_device=arguments.wait, vid=arguments.vid, 
            pid=arguments.pid, os_override=arguments.platform, override_checks=arguments.skip_checks)
except IOError as e:
    print(e)
    sys.exit(-1)`

This code looks valid.

**Comment by MichaelMackus** [comment]
Thanks @soramente ... this one should be able to be closed!

OP probably got confused on the usage of switch vs. self (different concepts).

Cheers!

**Comment by anowlcalledjosh** [comment]
It may be valid, but it's not correct. The function definitely should use `self` – when it's called, `self` and `switch` are the same object, but they wouldn't necessarily be if the class was used elsewhere.
