### ISSUE TITLE
No longer able to access homebrew menu with firmware 5.1.0

### ISSUE THREAD

**Issue by sacredbanana** [reswitched/fusee-launcher#22]
The new firmware causes a black screen instead of the homebrew menu when you select the album

**Comment by NightHammer1000** [comment]
Wrong project bro

**Comment by sacredbanana** [comment]
I know

**Comment by thisismike97** [comment]
@sacredbanana You didn't know, otherwise you would not have posted this issue...

All the devs are already aware it doesn't work on 5.1 so just close this issue and wait patiently.
