### ISSUE TITLE
No module named usb

### ISSUE THREAD

**Issue by danielandross** [reswitched/fusee-launcher#24]
Does this mean my Switch is not found or is there an issue with the pyusb version? Tried this on ubuntu 14 and 16.
```
sudo ./fusee-launcher.py payload.bin 
Traceback (most recent call last):
  File "./fusee-launcher.py", line 594, in <module>
    pid=arguments.pid, os_override=arguments.platform, override_checks=arguments.skip_checks)
  File "./fusee-launcher.py", line 466, in __init__
    self.dev = self._find_device(vid, pid)
  File "./fusee-launcher.py", line 496, in _find_device
    return self.backend.find_device(vid, pid)
  File "./fusee-launcher.py", line 133, in find_device
    import usb
ImportError: No module named 'usb'

```

**Comment by jakibaki** [comment]
This is an import error. 

That means that it failed **before** the script could even execute.  
So yeah, it's the pyusb-version (or rather a lack of pyusb) which is causing that.

Make sure that you actually have the python3-version of pyusb installed.

**Comment by Qyriad** [comment]
This is not a support forum.

**Comment by danielandross** [comment]
thanks @jakibaki I installed the wrong pyusb version as you assumed.

**Comment by joemsak** [comment]
Regardless of the maintainer's attitude in their own issues page (where people post, um, issues, for um, support), I'm glad this was here for me to help myself fix the same issue.
